version: "3.8"
services:
  postgres:
    image: postgres:12.8-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my-project"

  mongo:
    image: mongo:6.0.7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  redis:
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
